// Generated by CoffeeScript 1.10.0

/*
 * parse brown templates in json
 */

(function() {
  var brown;

  brown = require('brown');

  brown.indent = function(chars, key, char) {
    var i, j, ref, value;
    char = char || " ";
    value = brown.render("{{" + key + "}}", this);
    if (value.length < chars) {
      for (i = j = 0, ref = chars - value.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        value += char;
      }
    }
    return value;
  };

  module.exports = (function(app, data, next) {
    if (app.verbosity > 1) {
      console.log("parser::brown");
    }
    data.message = brown.render(data.template || data.message, data);
    return next(data);
  }).bind({});

}).call(this);
