// Generated by CoffeeScript 1.10.0

/*
 * detect channels by scanning for hashtags
 */

(function() {
  module.exports = (function(app, data, next) {
    var hashtags, i, len, tag;
    if (app.verbosity > 1) {
      console.log("parser::channeldetect");
    }
    data.channels = data.channels || [];
    if ((data.message != null) && data.message[0] === "#") {
      hashtags = data.message.match(/#[\w]+(?=\s|$)/g);
      if (hashtags) {
        for (i = 0, len = hashtags.length; i < len; i++) {
          tag = hashtags[i];
          data.channels.push(tag);
          data.message = String(data.message).replace(new RegExp(tag + "[ ]?"), "");
        }
      }
    }
    return next(data);
  }).bind({});

}).call(this);
