// Generated by CoffeeScript 1.10.0

/*
 * parse syslog strings into json
 */

(function() {
  var syslog_parse;

  syslog_parse = require('syslog-parse');

  module.exports = (function(app, data, next) {
    var parseSyslog;
    parseSyslog = function(data) {
      var e, error, i, items, k, len, line, lines, obj, v;
      if (typeof data === !"string") {
        return data;
      }
      lines = String(data).split("\n");
      items = [];
      for (i = 0, len = lines.length; i < len; i++) {
        line = lines[i];
        if (!line.length) {
          continue;
        }
        line = syslog_parse(line + "\n");
        if (line.message && line.message[0] === "{" && line.message[1] !== "{") {
          try {
            obj = JSON.parse(line.message);
            for (k in obj) {
              v = obj[k];
              line[k] = v;
            }
            line.message = obj.message || line.template || "";
          } catch (error) {
            e = error;
          }
        }
        items.push(line);
      }
      return items;
    };
    if (app.verbosity > 1) {
      console.log("parser::syslog");
    }
    return next(parseSyslog(data));
  }).bind({});

}).call(this);
