// Generated by CoffeeScript 1.10.0
(function() {
  var e, error, logserver;

  try {
    logserver = require('./index');
  } catch (error) {
    e = error;
    logserver = require('syslog++');
  }


  /*
   * inputs
   */

  require('syslogd-middleware/src/input/syslog')(logserver);


  /*
   * parsers
   */

  logserver.use(require('syslogd-middleware/src/parser/syslog'));

  logserver.use(require('syslogd-middleware/src/parser/brown'));


  /*
   * outputs
   */

  logserver.outputs.push(require('syslogd-middleware/src/output/stdout'));

}).call(this);
