// Generated by CoffeeScript 1.10.0
(function() {
  var _;

  _ = {
    isArray: function(a) {
      return Object.prototype.toString.call(a) === "[object Array]";
    }
  };

  module.exports = (function() {
    var me;
    me = this;
    this.outputs = [];
    this.middleware = [];
    this.verbosity = parseInt(process.env.DEBUG) || 1;
    this.use = function(cb) {
      return me.middleware.push(cb);
    };
    this.process = function(data) {
      var i, next;
      i = 0;
      next = function(result) {
        var action, cb, j, k, len, ref, results, results1, ri;
        if (me.middleware[++i] != null) {
          cb = me.middleware[i];
          if (_.isArray(result)) {
            results = [];
            for (j = 0, len = result.length; j < len; j++) {
              ri = result[j];
              results.push(cb(me, ri, next));
            }
            return results;
          } else {
            return cb(me, result, next);
          }
        } else {
          ref = me.outputs;
          results1 = [];
          for (k in ref) {
            action = ref[k];
            results1.push(action(me, result));
          }
          return results1;
        }
      };
      return me.middleware[i](me, data, next);
    };
    return this;
  }).apply({});

}).call(this);
