#!/bin/bash
find src -name "*.coffee" | grep -v node_modules | while read file; do
  echo "compiling ${file/coffee$/js/g}";
  slug="$(dirname "$file")" ; outdir="${slug/src/lib}"
  coffee -o "$outdir" -c "$file" ; git add "${file/coffee$/js/}";
done
