// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var serveTCP, serveUDP;
    if (app.verbosity > 1) {
      console.log("input::syslog");
    }
    serveUDP = function(host, port) {
      var dgram, server;
      dgram = require('dgram');
      server = dgram.createSocket('udp4');
      server.on('listening', function() {
        var address;
        address = server.address();
        console.log('input::syslog UDP Server listening on ' + address.address + ':' + address.port);
      });
      server.on('message', function(data, remote) {
        app.process(data.toString());
      });
      return server.bind(port, host);
    };
    serveTCP = function(host, port) {
      var clients, net, server;
      net = require('net');
      clients = [];
      server = net.createServer(function(socket) {
        var broadcast, close;
        socket.on('data', function(data) {
          return app.process(data);
        });
        close = function(data) {
          return clients.splice(clients.indexOf(socket), 1);
        };
        socket.on('end', close);
        socket.on('close', close);
        broadcast = function(message, sender) {
          clients.forEach(function(client) {
            if (client === sender) {
              return;
            }
            client.write(message);
          });
          process.stdout.write(message);
        };
      });
      console.log('input::syslog TCP Server listening on ' + host + ':' + port);
      return server.listen(port, host);
    };
    serveTCP(process.env.SYSLOG_HOST || '127.0.0.1', process.env.SYSLOG_TCP_PORT || 1339);
    serveUDP(process.env.SYSLOG_HOST || '127.0.0.1', process.env.SYSLOG_UDP_PORT || 1338);
  };

}).call(this);
