// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var serveTCP, serveUDP;
    if (app.verbosity > 1) {
      console.log("action::stdout");
    }
    serveUDP = function(host, port) {
      var dgram, server;
      dgram = require('dgram');
      server = dgram.createSocket('udp4');
      server.on('listening', function() {
        var address;
        address = server.address();
        console.log('input::syslog UDP Server listening on ' + address.address + ':' + address.port);
      });
      server.on('message', function(data, remote) {
        app.process(data.toString());
      });
      return server.bind(port, host);
    };
    serveTCP = function(host, port) {
      var net, server;
      net = require('net');
      server = net.createServer(function(socket) {
        console.log('input::syslog UDP Server listening on ' + address.address + ':' + address.port);
        socket.on('data', function(data) {
          return app.process(data);
        });
        socket.on('close', function(data) {
          return console.log('input:syslog TCP connection CLOSED');
        });
      });
      return server.listen(port, host);
    };
    serveUDP(process.env.SYSLOG_HOST || '127.0.0.1', process.env.SYSLOG_UDP_PORT || 1338);
    return serveTCP(process.env.SYSLOG_HOST || '127.0.0.1', process.env.SYSLOG_TCP_PORT || 1339);
  };

}).call(this);
